//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GADproject3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GADproject3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a221b3dcd6018_7087169615121846378412 {
            get {
                object obj = ResourceManager.GetObject("5a221b3dcd6018.7087169615121846378412", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a35912e88ad56_6643673715134600145598 {
            get {
                object obj = ResourceManager.GetObject("5a35912e88ad56.6643673715134600145598", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _776_7760866_south_african_smart_money {
            get {
                object obj = ResourceManager.GetObject("776-7760866_south-african-smart-money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forex_logo_png_transparent {
            get {
                object obj = ResourceManager.GetObject("forex-logo-png-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bank_question_indian_financial_system_code_finance_5b0f5f02c8fa58_5550989415277340188232 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bank-question-indian-financial-system-code-finance-5b0f5f02c8fa58.5550989" +
                        "415277340188232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_candlestick_pattern_candlestick_chart_foreign_exch_creative_crows_5ae6ad9917e281_2185244315250671610978 {
            get {
                object obj = ResourceManager.GetObject("kisspng-candlestick-pattern-candlestick-chart-foreign-exch-creative-crows-5ae6ad9" +
                        "917e281.2185244315250671610978", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_benchmarking_computer_software_clip_5ad795b096d809_0153599715240780006179 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-benchmarking-computer-software-clip-5ad795b096d809.0153599" +
                        "715240780006179", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_digital_marketing_market_research_consultant_busin_5b3b68aaed3859_6893368615306200749717 {
            get {
                object obj = ResourceManager.GetObject("kisspng-digital-marketing-market-research-consultant-busin-5b3b68aaed3859.6893368" +
                        "615306200749717", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_financial_accounting_accountant_bookkeeping_clip_a_portfolio_5abcd7202d5e05_3055835215223252801858 {
            get {
                object obj = ResourceManager.GetObject("kisspng-financial-accounting-accountant-bookkeeping-clip-a-portfolio-5abcd7202d5e" +
                        "05.3055835215223252801858", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_home_assistant_computer_icons_home_automation_kits_5b2beb86ae54e0_8600300515296049987141 {
            get {
                object obj = ResourceManager.GetObject("kisspng-home-assistant-computer-icons-home-automation-kits-5b2beb86ae54e0.8600300" +
                        "515296049987141", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_pdf_adobe_acrobat_computer_icons_pdf_icon_5b23e6c8e168c0_9082328015290794969233 {
            get {
                object obj = ResourceManager.GetObject("kisspng-pdf-adobe-acrobat-computer-icons-pdf-icon-5b23e6c8e168c0.9082328015290794" +
                        "969233", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_stock_market_day_trading_trader_option_5b19ec9c82d853_377141481528425628536 {
            get {
                object obj = ResourceManager.GetObject("kisspng-stock-market-day-trading-trader-option-5b19ec9c82d853.3771414815284256285" +
                        "36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_stock_market_day_trading_trader_option_5b19ec9c82d8531 {
            get {
                object obj = ResourceManager.GetObject("kisspng-stock-market-day-trading-trader-option-5b19ec9c82d8531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_stock_trader_day_trading_analyst_5aba2d669ad811_8506791315221507586342 {
            get {
                object obj = ResourceManager.GetObject("kisspng-stock-trader-day-trading-analyst-5aba2d669ad811.8506791315221507586342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_technology_strategy_business_content_strategy_orga_5b3ba246196815_5083051815306348221041 {
            get {
                object obj = ResourceManager.GetObject("kisspng-technology-strategy-business-content-strategy-orga-5b3ba246196815.5083051" +
                        "815306348221041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_trader_computer_icons_foreign_exchange_market_busi_5b2c804058c784_5969148615296430723637 {
            get {
                object obj = ResourceManager.GetObject("kisspng-trader-computer-icons-foreign-exchange-market-busi-5b2c804058c784.5969148" +
                        "615296430723637", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_vladimir_school_educational_institution_planning_i_pen_diary_5a8bffbfed1655_1088503615191244159711 {
            get {
                object obj = ResourceManager.GetObject("kisspng-vladimir-school-educational-institution-planning-i-pen-diary-5a8bffbfed16" +
                        "55.1088503615191244159711", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_forex_signal_foreign_exchange_market_trader_service_business_business_service_people_investment_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-forex-signal-foreign-exchange-market-trader-service-business-busi" +
                        "ness-service-people-investment-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_forex_signal_foreign_exchange_market_trader_service_business_business_service_people_investment_thumbnail1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-forex-signal-foreign-exchange-market-trader-service-business-busi" +
                        "ness-service-people-investment-thumbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SL_022321_41020_04 {
            get {
                object obj = ResourceManager.GetObject("SL-022321-41020-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SL_022321_41020_041 {
            get {
                object obj = ResourceManager.GetObject("SL-022321-41020-041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slide_1_graph {
            get {
                object obj = ResourceManager.GetObject("slide-1-graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slide_1_graph1 {
            get {
                object obj = ResourceManager.GetObject("slide-1-graph1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
